name: crm_frontend_deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # Ensure LTS version

      - name: Build the React project
        env:
          REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL_crm }}
        run: |
          npm ci
          npm run build

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy build to EC2 via SCP & SSH
        run: |
          scp -r -o StrictHostKeyChecking=no build ubuntu@${{ secrets.SERVER_IP }}:/home/ubuntu/frontend-build

          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_IP }} << 'EOF'
            # Setup Node.js & PM2 if not already installed
            curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
            sudo apt-get install -y nodejs
            sudo npm install -g pm2

            # Move to deployment directory
            mkdir -p /home/ubuntu/frontend
            rm -rf /home/ubuntu/frontend/*
            mv /home/ubuntu/frontend-build/* /home/ubuntu/frontend/

            # Restart PM2 or start if not already running
            pm2 delete frontend || true
            pm2 serve /home/ubuntu/frontend 3000 --name frontend --spa
          EOF
