name: crm_frontend_deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # Use LTS if possible (e.g., 20)

      - name: Install dependencies and build React project
        run: |
          npm ci
          npm run build
        env:
          REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL_crm }}
          CI: false  # Prevent React/ESLint from treating warnings as errors

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy build to EC2 via SCP & SSH
        run: |
          # Copy build folder to remote server
          scp -r -o StrictHostKeyChecking=no build ubuntu@${{ secrets.SERVER_IP }}:/home/ubuntu/frontend-build

          # SSH into the server and set up deployment
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_IP }} << 'EOF'
            # Install Node.js & PM2 if not already installed
            curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
            sudo apt-get install -y nodejs
            sudo npm install -g pm2

            # Deploy the new build
            mkdir -p /home/ubuntu/frontend
            rm -rf /home/ubuntu/frontend/*
            mv /home/ubuntu/frontend-build/* /home/ubuntu/frontend/

            # Restart frontend via PM2
            pm2 delete frontend || true
            pm2 serve /home/ubuntu/frontend 3000 --name frontend --spa
          EOF
